## Environment

development:
  host: <%= ENV['DEVISE_LDAP_HOST'] %>
  port: <%= ENV['DEVISE_LDAP_PORT'] %>
  attribute: <%= ENV['DEVISE_LDAP_ATTRIBUTE'] %>
  base: <%= ENV['DEVISE_LDAP_BASE'] %>
  admin_user: <%= ENV['DEVISE_LDAP_ADMIN'] %>
  admin_password: <%= ENV['DEVISE_LDAP_ADMIN_PW'] %>
  ssl: <%= ENV['DEVISE_LDAP_SSL'] %>

test:
  host: <%= ENV['DEVISE_LDAP_HOST'] %>
  port: <%= ENV['DEVISE_LDAP_PORT'] %>
  attribute: <%= ENV['DEVISE_LDAP_ATTRIBUTE'] %>
  base: <%= ENV['DEVISE_LDAP_BASE'] %>
  admin_user: <%= ENV['DEVISE_LDAP_ADMIN'] %>
  admin_password: <%= ENV['DEVISE_LDAP_ADMIN_PW'] %>
  ssl: <%= ENV['DEVISE_LDAP_SSL'] %>

production:
  host: <%= ENV['DEVISE_LDAP_HOST'] %>
  port: <%= ENV['DEVISE_LDAP_PORT'] %>
  attribute: <%= ENV['DEVISE_LDAP_ATTRIBUTE'] %>
  base: <%= ENV['DEVISE_LDAP_BASE'] %>
  admin_user: <%= ENV['DEVISE_LDAP_ADMIN'] %>
  admin_password: <%= ENV['DEVISE_LDAP_ADMIN_PW'] %>
  ssl: <%= ENV['DEVISE_LDAP_SSL'] %>
  require_attribute_presence:
    mail: true
